#!/bin/bash

NPU=$1
if [ "$NPU" == "v1" ]; then
    export VSIMULATOR_SHADER_CORE_COUNT=0.5
    export VSIMULATOR_CONFIG=VIP9000PICO_PID0XEE
elif [ "$NPU" == "v2" ]; then
    export VSIMULATOR_SHADER_CORE_COUNT=1
    export VSIMULATOR_CONFIG=VIP9000NANOSI_PLUS_PID0X10000016
elif [ "$NPU" == "v3" ]; then
    export VSIMULATOR_SHADER_CORE_COUNT=1
    export VSIMULATOR_CONFIG=VIP9000NANODI_PLUS_PID0X1000003B
fi

